package fiuba.algo3.tp2.modelo.UnidadFactory;

public enum PiezaType {

    UNIDAD_ALDEANO, UNIDAD_ESPADACHIN, UNIDAD_ARMADEASEDIO, UNIDAD_ARQUERO, EDIFICIO_CASTILLO, EDIFICIO_CUARTEL, EDIFICIO_PLAZACENTRAL,

}